name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        component: [features, training, serving/batch, serving/online, monitoring]
    uses: ViniciusOtoni/mlops-platform/.github/workflows/ci-validate.yml@main
    with:
      working-directory: ${{ matrix.component }}
      check-version-tag: false
      validate-bundle: true
    secrets: inherit
